name: Build, Test, Pack and Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-test-pack-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore Serilog.Sinks.FastDB.slnx

      - name: Build
        run: dotnet build Serilog.Sinks.FastDB.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test Serilog.Sinks.FastDB.slnx --configuration Release --no-build

      - name: Pack
        run: dotnet pack Serilog.Sinks.FastDB.csproj --configuration Release --no-build --output ./artifacts

      - name: Publish to NuGet.org (Trusted Publishing)
        run: dotnet nuget push "./artifacts/*.nupkg" --source "https://api.nuget.org/v3/index.json" --skip-duplicate
